name: Deploy to Production

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to server
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.GCP_VM_HOST }}
        username: ${{ secrets.GCP_VM_USER }}
        key: ${{ secrets.GCP_VM_SSH_KEY }}
        script: |
          cd /var/www/app-teste-ci

          # Corrigir problema do Git "dubious ownership"
          git config --global --add safe.directory /var/www/app-teste-ci

          # Corrigir permissões do .git para evitar erro de fetch
          sudo chown -R www-data:www-data .git

          # Atualizar código
          git fetch --all
          git reset --hard origin/main

          # Garantir que os diretórios existam
          sudo mkdir -p writable/{cache,logs,session,uploads}

          # Corrigir permissões de execução
          sudo chown -R www-data:www-data writable/ .git
          sudo chmod -R 775 writable/

          # Instalar dependências PHP
          if [ -f "composer.json" ]; then
            composer install --no-interaction --prefer-dist --optimize-autoloader
          fi

          # Reiniciar serviços
          sudo systemctl reload nginx
          sudo systemctl reload php8.2-fpm

          echo "✅ Deploy completed successfully!"
